export const DEFAULT_TELNET_PORT = 8081;
export const DEFAULT_TIMEOUT_MS = 10000;
export const LINE_DELIMITER = "\r\n";

export const TELNET_COMMANDS = {
	// Player Management
	admin: { category: "Player Management", usage: "admin <add|remove|list> [player] [level]", minLevel: 0 },
	ban: { category: "Player Management",
		usage: "ban <add|remove|list> [player] [duration] [unit] [reason]",
		minLevel: 1,
	},
	kick: { category: "Player Management", usage: "kick <player> [reason]", minLevel: 1 },
	kickall: { category: "Player Management", usage: "kickall [reason]", minLevel: 1 },
	kill: { category: "Player Management", usage: "kill <player or entityId>", minLevel: 1 },
	killall: { category: "Player Management", usage: "killall", minLevel: 1 },
	listplayerids: { category: "Player Management", usage: "listplayerids (lpi)", minLevel: 1000 },
	listplayers: { category: "Player Management", usage: "listplayers (lp)", minLevel: 1000 },
	listknownplayers: { category: "Player Management", usage: "listknownplayers [filter]", minLevel: 1000 },
	whitelist: { category: "Player Management", usage: "whitelist <add|remove|list> [player]", minLevel: 0 },
	teleportplayer: { category: "Player Management",
		usage: "teleportplayer <player> <x> <y> <z|player> (tele)",
		minLevel: 1,
	},
	sayplayer: { category: "Player Management", usage: "sayplayer <player> <message> (pm)", minLevel: 1 },
	showinventory: { category: "Player Management", usage: "showinventory <player>", minLevel: 1 },
	playerOwnedEntities: { category: "Player Management", usage: "playerOwnedEntities (poe)", minLevel: 1000 },
	pplist: { category: "Player Management", usage: "pplist", minLevel: 1000 },
	printpinfo: { category: "Player Management", usage: "printpinfo", minLevel: 1000 },
	reply: { category: "Player Management", usage: "reply <message> (re)", minLevel: 1 },

	// Permission & Admin
	commandpermission: { category: "Permission & Admin",
		usage: "commandpermission <add|remove|list> [command] [level] (cp)",
		minLevel: 0,
	},
	permissionsallowed: { category: "Permission & Admin",
		usage: "permissionsallowed <mask> (pallowed|pa)",
		minLevel: 0,
	},
	overridemaxplayercount: { category: "Permission & Admin",
		usage: "overridemaxplayercount <count>",
		minLevel: 0,
	},
	createwebuser: { category: "Permission & Admin", usage: "createwebuser", minLevel: 0 },
	webpermission: { category: "Permission & Admin", usage: "webpermission", minLevel: 0 },
	webtokens: { category: "Permission & Admin", usage: "webtokens", minLevel: 0 },

	// World Management
	saveworld: { category: "World Management", usage: "saveworld (sa)", minLevel: 0 },
	shutdown: { category: "World Management", usage: "shutdown", minLevel: 0 },
	chunkreset: { category: "World Management", usage: "chunkreset <x> <z> (cr)", minLevel: 0 },
	regionreset: { category: "World Management", usage: "regionreset [region] (rr)", minLevel: 0 },
	rendermap: { category: "World Management", usage: "rendermap", minLevel: 0 },
	generatemap: { category: "World Management", usage: "generatemap", minLevel: 0 },
	visitmap: { category: "World Management", usage: "visitmap [x] [z] (vpois|visitpois)", minLevel: 0 },
	agemap: { category: "World Management", usage: "agemap", minLevel: 0 },
	expiryinfo: { category: "World Management", usage: "expiryinfo", minLevel: 0 },
	repairchunkdensity: { category: "World Management",
		usage: "repairchunkdensity <x> <z> [fix] (rcd)",
		minLevel: 0,
	},
	chunkcache: { category: "World Management", usage: "chunkcache (cc)", minLevel: 1000 },
	chunkobserver: { category: "World Management", usage: "chunkobserver <x> <y> <z> [range] (co)", minLevel: 0 },
	showchunkdata: { category: "World Management", usage: "showchunkdata (sc)", minLevel: 1000 },
	resetallstats: { category: "World Management", usage: "resetallstats [true]", minLevel: 0 },
	exportcurrentconfigs: { category: "World Management", usage: "exportcurrentconfigs", minLevel: 0 },
	exportprefab: { category: "World Management", usage: "exportprefab", minLevel: 0 },
	smoothpoi: { category: "World Management", usage: "smoothpoi", minLevel: 0 },
	smoothworldall: { category: "World Management", usage: "smoothworldall (swa)", minLevel: 0 },
	prefab: { category: "World Management", usage: "prefab <subcommand>", minLevel: 0 },
	prefabeditor: { category: "World Management", usage: "prefabeditor (prefabedit|pedit)", minLevel: 0 },
	prefabupdater: { category: "World Management", usage: "prefabupdater", minLevel: 0 },
	placeblockrotations: { category: "World Management", usage: "placeblockrotations (pbr)", minLevel: 1000 },
	placeblockshapes: { category: "World Management", usage: "placeblockshapes (pbs)", minLevel: 1000 },
	pois: { category: "World Management", usage: "pois <on|off>", minLevel: 1000 },
	poiwaypoints: { category: "World Management", usage: "poiwaypoints <filter> (pwp)", minLevel: 1000 },
	tppoi: { category: "World Management", usage: "tppoi", minLevel: 1000 },
	teleportpoirelative: { category: "World Management", usage: "teleportpoirelative (tppr)", minLevel: 1000 },
	trees: { category: "World Management", usage: "trees <on|off>", minLevel: 1000 },
	mapdata: { category: "World Management", usage: "mapdata", minLevel: 0 },

	// Entity Control
	listents: { category: "Entity Control", usage: "listents (le)", minLevel: 1000 },
	spawnentity: { category: "Entity Control", usage: "spawnentity [playerId] [entityId] (se)", minLevel: 0 },
	spawnentityat: { category: "Entity Control",
		usage: "spawnentityat <entityId> <x> <y> <z> (sea)",
		minLevel: 0,
	},
	spawnwanderinghorde: { category: "Entity Control", usage: "spawnwanderinghorde (spawnw)", minLevel: 0 },
	spawnscouts: { category: "Entity Control", usage: "spawnscouts [player] [x] [y] [z]", minLevel: 0 },
	spawnairdrop: { category: "Entity Control", usage: "spawnairdrop", minLevel: 0 },
	spawnsupplycrate: { category: "Entity Control", usage: "spawnsupplycrate", minLevel: 0 },
	shownexthordetime: { category: "Entity Control", usage: "shownexthordetime", minLevel: 1000 },
	bents: { category: "Entity Control", usage: "bents <on|off|count>", minLevel: 1000 },
	sdcs: { category: "Entity Control", usage: "sdcs <subcommand>", minLevel: 0 },
	lock: { category: "Entity Control", usage: "lock", minLevel: 0 },

	// Player State
	buff: { category: "Player State", usage: "buff <buffName>", minLevel: 1000 },
	buffplayer: { category: "Player State", usage: "buffplayer <player> <buffName>", minLevel: 1 },
	debuff: { category: "Player State", usage: "debuff <buffName>", minLevel: 1000 },
	debuffplayer: { category: "Player State", usage: "debuffplayer <player> <buffName>", minLevel: 1 },
	giveself: { category: "Player State", usage: "giveself <itemName> [quality=6] [count=1] [putInInventory=false] [spawnWithMods=true]", minLevel: 1000 },
	giveselfxp: { category: "Player State", usage: "giveselfxp <amount>", minLevel: 1000 },
	givexp: { category: "Player State", usage: "givexp <player> <amount>", minLevel: 1 },
	give: { category: "Player State", usage: "give <player> <itemName> <amount>", minLevel: 1 },
	givequest: { category: "Player State", usage: "givequest <questName> [tier]", minLevel: 1 },
	removequest: { category: "Player State", usage: "removequest <questName>", minLevel: 1 },
	gamestage: { category: "Player State", usage: "gamestage", minLevel: 1000 },
	starve: { category: "Player State", usage: "starve [percent] (hungry|food)", minLevel: 1000 },
	thirsty: { category: "Player State", usage: "thirsty [percent]", minLevel: 1000 },
	exhausted: { category: "Player State", usage: "exhausted", minLevel: 1000 },
	sleep: { category: "Player State", usage: "sleep <seconds>", minLevel: 1000 },
	spectator: { category: "Player State", usage: "spectator (spectatormode|sm)", minLevel: 1000 },
	automove: { category: "Player State", usage: "automove", minLevel: 1000 },
	calibrate: { category: "Player State", usage: "calibrate (calib)", minLevel: 1000 },
	fov: { category: "Player State", usage: "fov <value>", minLevel: 1000 },
	camera: { category: "Player State", usage: "camera <lock|unlock|load|save> (cam)", minLevel: 1000 },
	creativemenu: { category: "Player State", usage: "creativemenu [on|off] (cm)", minLevel: 0 },
	debugmenu: { category: "Player State", usage: "debugmenu [on|off] (dm)", minLevel: 0 },
	debugpanels: { category: "Player State", usage: "debugpanels [on|off]", minLevel: 0 },
	debugshot: { category: "Player State", usage: "debugshot (dbs)", minLevel: 1000 },
	show: { category: "Player State", usage: "show <layer>", minLevel: 1000 },
	showalbedo: { category: "Player State", usage: "showalbedo [on|off] (albedo)", minLevel: 1000 },
	shownormals: { category: "Player State", usage: "shownormals [on|off] (norms)", minLevel: 1000 },
	showspecular: { category: "Player State", usage: "showspecular [on|off] (spec)", minLevel: 1000 },
	showswings: { category: "Player State", usage: "showswings", minLevel: 1000 },
	showhits: { category: "Player State", usage: "showhits", minLevel: 1000 },
	showtriggers: { category: "Player State", usage: "showtriggers <visibility>", minLevel: 1000 },
	togglelm: { category: "Player State", usage: "togglelm", minLevel: 1000 },
	ScreenEffect: { category: "Player State", usage: "ScreenEffect <effect>", minLevel: 1000 },
	spawnscreen: { category: "Player State", usage: "spawnscreen", minLevel: 1000 },
	switchview: { category: "Player State", usage: "switchview (sv)", minLevel: 1000 },
	squarespiral: { category: "Player State", usage: "squarespiral (sqs)", minLevel: 1000 },
	playervisitmap: { category: "Player State", usage: "playervisitmap <x> <z> <w> <d> [log] (pvm)", minLevel: 0 },

	// Game Settings
	getgamepref: { category: "Game Settings", usage: "getgamepref [filter] (gg)", minLevel: 1000 },
	setgamepref: { category: "Game Settings", usage: "setgamepref <prefName> <value> (sg)", minLevel: 0 },
	getgamestat: { category: "Game Settings", usage: "getgamestat [filter] (ggs)", minLevel: 1000 },
	setgamestat: { category: "Game Settings", usage: "setgamestat <statName> <value> (sgs)", minLevel: 0 },
	gettime: { category: "Game Settings", usage: "gettime (gt)", minLevel: 1000 },
	settime: { category: "Game Settings", usage: "settime <day|night|time|day hour minute> (st)", minLevel: 0 },
	settempunit: { category: "Game Settings", usage: "settempunit <c|f> (stu)", minLevel: 1000 },
	setwatervalue: { category: "Game Settings", usage: "setwatervalue <value> (swv)", minLevel: 0 },
	settargetfps: { category: "Game Settings", usage: "settargetfps <fps>", minLevel: 0 },
	getoptions: { category: "Game Settings", usage: "getoptions", minLevel: 1000 },
	getlogpath: { category: "Game Settings", usage: "getlogpath (glp)", minLevel: 1000 },
	config: { category: "Game Settings", usage: "config <import|export> <path>", minLevel: 0 },
	cvar: { category: "Game Settings", usage: "cvar <set|get|track|list> [name] [value]", minLevel: 0 },
	setcvar: { category: "Game Settings", usage: "setcvar <name> <value>", minLevel: 0 },
	weather: { category: "Game Settings", usage: "weather <setting>", minLevel: 0 },
	weathersurvival: { category: "Game Settings", usage: "weathersurvival <on|off>", minLevel: 0 },
	newweathersurvival: { category: "Game Settings", usage: "newweathersurvival <on|off>", minLevel: 0 },
	debugweather: { category: "Game Settings", usage: "debugweather", minLevel: 1000 },
	spectrum: { category: "Game Settings", usage: "spectrum <name>", minLevel: 0 },
	ForceEventDate: { category: "Game Settings", usage: "ForceEventDate <date>", minLevel: 0 },

	// Debug & Performance
	mem: { category: "Debug & Performance", usage: "mem", minLevel: 1000 },
	memcl: { category: "Debug & Performance", usage: "memcl", minLevel: 1000 },
	listthreads: { category: "Debug & Performance", usage: "listthreads (lt)", minLevel: 1000 },
	loggamestate: { category: "Debug & Performance", usage: "loggamestate <message> [true|false] (lgs)", minLevel: 0 },
	loglevel: { category: "Debug & Performance",
		usage: "loglevel <INF|WRN|ERR|EXC|ALL> <true|false>",
		minLevel: 0,
	},
	clear: { category: "Debug & Performance", usage: "clear", minLevel: 1000 },
	memprofile: { category: "Debug & Performance", usage: "memprofile (mprof)", minLevel: 1000 },
	profiler: { category: "Debug & Performance", usage: "profiler", minLevel: 1000 },
	profiling: { category: "Debug & Performance", usage: "profiling", minLevel: 1000 },
	profilenetwork: { category: "Debug & Performance", usage: "profilenetwork", minLevel: 1000 },
	meshdatamanager: { category: "Debug & Performance", usage: "meshdatamanager (mdm)", minLevel: 1000 },
	exception: { category: "Debug & Performance", usage: "exception <message>", minLevel: 0 },
	testloop: { category: "Debug & Performance", usage: "testloop", minLevel: 0 },
	unittest: { category: "Debug & Performance", usage: "unittest", minLevel: 0 },
	SystemInfo: { category: "Debug & Performance", usage: "SystemInfo", minLevel: 1000 },
	occlusion: { category: "Debug & Performance", usage: "occlusion <subcommand>", minLevel: 1000 },
	testoccreport: { category: "Debug & Performance", usage: "testoccreport (toccr)", minLevel: 1000 },
	openiddebug: { category: "Debug & Performance", usage: "openiddebug <on|off>", minLevel: 0 },

	// Communication
	say: { category: "Communication", usage: "say <message>", minLevel: 1 },
	help: { category: "Communication", usage: "help [command]", minLevel: 1000 },
	version: { category: "Communication", usage: "version", minLevel: 1000 },
	versionui: { category: "Communication", usage: "versionui", minLevel: 1000 },

	// Lists & Lookup
	listitems: { category: "Lists & Lookup", usage: "listitems [filter] (li)", minLevel: 1000 },
	listdlc: { category: "Lists & Lookup", usage: "listdlc (dlcs)", minLevel: 1000 },
	listgameobjects: { category: "Lists & Lookup", usage: "listgameobjects (lgo)", minLevel: 1000 },
	listpes: { category: "Lists & Lookup", usage: "listpes [name]", minLevel: 1000 },

	// AI & Director
	ai: { category: "AI & Director", usage: "ai <subcommand>", minLevel: 0 },
	aiddebug: { category: "AI & Director", usage: "aiddebug", minLevel: 0 },
	utilityai: { category: "AI & Director", usage: "utilityai (uai)", minLevel: 0 },
	actiondelay: { category: "AI & Director", usage: "actiondelay [seconds] (ad)", minLevel: 0 },
	adjustmarkup: { category: "AI & Director", usage: "adjustmarkup", minLevel: 0 },
	dialog: { category: "AI & Director", usage: "dialog (dialogs)", minLevel: 0 },
	sleeper: { category: "AI & Director", usage: "sleeper", minLevel: 1000 },

	// Rendering & Visuals
	enablerendering: { category: "Rendering & Visuals", usage: "enablerendering <on|off>", minLevel: 0 },
	showClouds: { category: "Rendering & Visuals", usage: "showClouds", minLevel: 1000 },
	lights: { category: "Rendering & Visuals", usage: "lights", minLevel: 1000 },
	gfx: { category: "Rendering & Visuals", usage: "gfx", minLevel: 1000 },
	graph: { category: "Rendering & Visuals", usage: "graph", minLevel: 1000 },

	// Network
	networkclient: { category: "Network", usage: "networkclient (netc)", minLevel: 1000 },
	networkserver: { category: "Network", usage: "networkserver (nets)", minLevel: 0 },

	// Audio
	audio: { category: "Audio", usage: "audio", minLevel: 1000 },
	dms: { category: "Audio", usage: "dms <subcommand>", minLevel: 1000 },
	mumblepositionalaudio: { category: "Audio", usage: "mumblepositionalaudio (mpa)", minLevel: 1000 },

	// Dynamic Mesh
	dynamicmesh: { category: "Dynamic Mesh", usage: "dynamicmesh (zz)", minLevel: 0 },
	dynamicmeshdebug: { category: "Dynamic Mesh", usage: "dynamicmeshdebug (zd)", minLevel: 0 },
	dynamicproperties: { category: "Dynamic Mesh", usage: "dynamicproperties (dprop)", minLevel: 1000 },

	// SCore / Utility Mods
	ReloadSCore: { category: "SCore / Utility Mods", usage: "ReloadSCore <xmlName>", minLevel: 0 },
	weaponsway: { category: "SCore / Utility Mods", usage: "weaponsway <args>", minLevel: 1000 },
	gears: { category: "SCore / Utility Mods", usage: "gears <args>", minLevel: 0 },
	quartz: { category: "SCore / Utility Mods", usage: "quartz <args>", minLevel: 0 },
	fireclear: { category: "SCore / Utility Mods", usage: "fireclear", minLevel: 0 },

	// BeyondStorage
	bsclearcache: { category: "BeyondStorage", usage: "bsclearcache", minLevel: 0 },
	bshelp: { category: "BeyondStorage", usage: "bshelp", minLevel: 1000 },
	bsreloadconfig: { category: "BeyondStorage", usage: "bsreloadconfig", minLevel: 0 },
	bssetconfig: { category: "BeyondStorage", usage: "bssetconfig <key> <value>", minLevel: 0 },
	bsshowconfig: { category: "BeyondStorage", usage: "bsshowconfig", minLevel: 1000 },

	// Discord / Twitch
	discord: { category: "Discord / Twitch", usage: "discord (dc)", minLevel: 1000 },
	twitch: { category: "Discord / Twitch", usage: "twitch <command> <params>", minLevel: 0 },
	twitchadmin: { category: "Discord / Twitch", usage: "twitchadmin", minLevel: 0 },

	// Misc Server
	AdminSpeed: { category: "Misc Server", usage: "AdminSpeed [value] (as)", minLevel: 0 },
	AccDecay: { category: "Misc Server", usage: "AccDecay [show|hide|reset|<value>] (SetAccDecay|SetAccuracyDecay|sad)", minLevel: 1000 },
	challenges: { category: "Misc Server", usage: "challenges <subcommand>", minLevel: 1000 },
	damagereset: { category: "Misc Server", usage: "damagereset", minLevel: 0 },
	decomgr: { category: "Misc Server", usage: "decomgr [state]", minLevel: 1000 },
	invalidatecaches: { category: "Misc Server", usage: "invalidatecaches", minLevel: 0 },
	maivd: { category: "Misc Server", usage: "maivd", minLevel: 1000 },
	na: { category: "Misc Server", usage: "na", minLevel: 1000 },
	pirs: { category: "Misc Server", usage: "pirs", minLevel: 1000 },
	plc: { category: "Misc Server", usage: "plc", minLevel: 1000 },
	stab: { category: "Misc Server", usage: "stab", minLevel: 1000 },
	tcs: { category: "Misc Server", usage: "tcs (testCoverSystem)", minLevel: 1000 },
	tls: { category: "Misc Server", usage: "tls", minLevel: 1000 },
	traderarea: { category: "Misc Server", usage: "traderarea", minLevel: 1000 },
	transformdebug: { category: "Misc Server", usage: "transformdebug (tdbg)", minLevel: 1000 },
	floatingorigin: { category: "Misc Server", usage: "floatingorigin (fo)", minLevel: 1000 },
	xui: { category: "Misc Server", usage: "xui <args>", minLevel: 0 },
	uioptions: { category: "Misc Server", usage: "uioptions <key> <value> (uio)", minLevel: 0 },
	reloadentityclasses: { category: "Misc Server", usage: "reloadentityclasses (rec)", minLevel: 0 },
	reloadlog: { category: "Misc Server", usage: "reloadlog (rlog)", minLevel: 1000 },
	wsmats: { category: "Misc Server", usage: "wsmats (workstationmaterials)", minLevel: 0 },

	// Search / Help Utilities
	search: { category: "Search / Help Utilities", usage: "search <string>", minLevel: 1000 },
	output: { category: "Search / Help Utilities", usage: "output", minLevel: 1000 },
	outputdetailed: { category: "Search / Help Utilities", usage: "outputdetailed", minLevel: 1000 },

	// NaiwaziBot / Custom Mod Commands (observed on this server)
	nwzbotblockfill: { category: "NaiwaziBot / Custom Mod", usage: "nwzbot-blockfill <args>", minLevel: 0 },
	nwzbotremoveentity: { category: "NaiwaziBot / Custom Mod", usage: "nwzbot-removeentity <args>", minLevel: 0 },
	nwzbot_test: { category: "NaiwaziBot / Custom Mod", usage: "nwzbot-test <args>", minLevel: 0 },
} as const;

export type CommandName = keyof typeof TELNET_COMMANDS;
